# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libmagick++-dev
r:
- 3.1
- 3.2
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE
